# Generated by Django 6.0.3 on 2026-05-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_emailverify'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='check_product_price',
        ),
    ]
